version: 2
updates:
  # Enable version updates for Yarn
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Include a message for the commit
    commit-message:
      prefix: 'chore'
      include: 'scope'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore'
      include: 'scope'
